version: '3'
services:
    base:
        build:
            context: base
            dockerfile: Dockerfile
            args:
                CMAKE_VERSION_FULL: ${CMAKE_VERSION_FULL}
                CMAKE_VERSION: ${CMAKE_VERSION}
                PYTHON_VERSION: ${PYTHON_VERSION}
                CONAN_VERSION: ${CONAN_VERSION}
        image: ${DOCKER_REPOSITORY}/base
        container_name: base
        tty: true
    gcc5:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 5.5.0
                CONAN_VERSION: ${CONAN_VERSION}
                DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
        image: ${DOCKER_REPOSITORY}/gcc5
        container_name: gcc5
        tty: true
    gcc6:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 6.5.0
                CONAN_VERSION: ${CONAN_VERSION}
                DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
        image: ${DOCKER_REPOSITORY}/gcc6
        container_name: gcc6
        tty: true
    gcc7:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 7.5.0
                CONAN_VERSION: ${CONAN_VERSION}
                DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
        image: ${DOCKER_REPOSITORY}/gcc7
        container_name: gcc7
        tty: true
    gcc8:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 8.4.0
                CONAN_VERSION: ${CONAN_VERSION}
                DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
        image: ${DOCKER_REPOSITORY}/gcc8
        container_name: gcc8
        tty: true
    gcc9:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 9.3.0
                CONAN_VERSION: ${CONAN_VERSION}
                DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
        image: ${DOCKER_REPOSITORY}/gcc9
        container_name: gcc9
        tty: true
        depends_on:
          - base
    gcc10:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 10.3.0
                CONAN_VERSION: ${CONAN_VERSION}
                DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
        image: ${DOCKER_REPOSITORY}/gcc10
        container_name: gcc10
        tty: true
    gcc11:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 11.1.0
                CONAN_VERSION: ${CONAN_VERSION}
                DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
        image: ${DOCKER_REPOSITORY}/gcc11
        container_name: gcc10
        tty: true
    clang9:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                LLVM_VERSION: 9.0.1
                CONAN_VERSION: ${CONAN_VERSION}
                DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
        image: ${DOCKER_REPOSITORY}/clang9
        container_name: clang9
        tty: true
    clang10:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                LLVM_VERSION: 10.0.1
                CONAN_VERSION: ${CONAN_VERSION}
                DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
        image: ${DOCKER_REPOSITORY}/clang10
        container_name: clang10
        tty: true
    clang11:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                LLVM_VERSION: 11.1.0
                CONAN_VERSION: ${CONAN_VERSION}
                DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
        image: ${DOCKER_REPOSITORY}/clang11
        container_name: clang11
        tty: true
    clang12:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                LLVM_VERSION: 12.0.0
                CONAN_VERSION: ${CONAN_VERSION}
                DOCKER_REPOSITORY: ${DOCKER_REPOSITORY}
        image: ${DOCKER_REPOSITORY}/clang12
        container_name: clang12
        tty: true
