version: '3'
services:
    base:
        build:
            context: base
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 10.3.0
        image: "uilianries/base"
        container_name: base
        tty: true
    gcc5-conanfy:
        build:
            context: conanfy
            dockerfile: gcc.Dockerfile
            args:
                GCC_VERSION: 5.5.0
        image: "uilianries/gcc5-conanfy"
        container_name: gcc5_conan
        tty: true
    gcc6-conanfy:
        build:
            context: conanfy
            dockerfile: gcc.Dockerfile
            args:
                GCC_VERSION: 6.5.0
        image: "uilianries/gcc6-conanfy"
        container_name: gcc6_conan
        tty: true
    gcc7-conanfy:
        build:
            context: conanfy
            dockerfile: gcc.Dockerfile
            args:
                GCC_VERSION: 7.5.0
        image: "uilianries/gcc7-conanfy"
        container_name: gcc7_conan
        tty: true
    gcc8-conanfy:
        build:
            context: conanfy
            dockerfile: gcc.Dockerfile
            args:
                GCC_VERSION: 8.4.0
        image: "uilianries/gcc8-conanfy"
        container_name: gcc8_conan
        tty: true
    gcc9-conanfy:
        build:
            context: conanfy
            dockerfile: gcc.Dockerfile
            args:
                GCC_VERSION: 9.3.0
        image: "uilianries/gcc9-conanfy"
        container_name: gcc9_conan
        tty: true
    gcc10-conanfy:
        build:
            context: conanfy
            dockerfile: gcc.Dockerfile
            args:
                GCC_VERSION: 10.3.0
        image: "uilianries/gcc10-conanfy"
        container_name: gcc10_conan
        tty: true
    clang4-conanfy:
        build:
            context: conanfy
            dockerfile: clang.Dockerfile
            args:
                LLVM_VERSION: 4.0.1
        image: "uilianries/clang4-conanfy"
        container_name: clang4_conan
        tty: true
    clang11-conanfy:
        build:
            context: conanfy
            dockerfile: clang.Dockerfile
            args:
                LLVM_VERSION: 11.1.0
        image: "uilianries/clang11-conanfy"
        container_name: clang11_conan
        tty: true
    gcc5:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 5.5.0
        image: "uilianries/gcc5"
        container_name: gcc5
        tty: true
    gcc6:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 6.5.0
        image: "uilianries/gcc6"
        container_name: gcc6
        tty: true
    gcc7:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 7.5.0
        image: "uilianries/gcc7"
        container_name: gcc7
        tty: true
    gcc8:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 8.4.0
        image: "uilianries/gcc8"
        container_name: gcc8
        tty: true
    gcc9:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 9.3.0
        image: "uilianries/gcc9"
        container_name: gcc9
        tty: true
        depends_on:
          - base
    gcc10:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 10.3.0
        image: "uilianries/gcc10"
        container_name: gcc10
        tty: true
    clang4:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                LLVM_VERSION: 4.0.1
        image: "uilianries/clang4"
        container_name: clang4
        tty: true
    clang11:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                LLVM_VERSION: 11.1.0
        image: "uilianries/clang11"
        container_name: clang11
        tty: true
