version: '3'
services:
    base:
        build:
            context: base
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 10.3.0
                CMAKE_VERSION: 3.19.6
                PYTHON_VERSION: 3.8.8
        image: "uilianries/base"
        container_name: base
        tty: true
    gcc5-conanfy:
        build:
            context: conanfy
            dockerfile: gcc.Dockerfile
            args:
                GCC_VERSION: 5.5.0
        image: "uilianries/gcc5-conanfy"
        container_name: gcc5_conanfy
        tty: true
    gcc6-conanfy:
        build:
            context: conanfy
            dockerfile: gcc.Dockerfile
            args:
                GCC_VERSION: 6.5.0
        image: "uilianries/gcc6-conanfy"
        container_name: gcc6_conanfy
        tty: true
    gcc7-conanfy:
        build:
            context: conanfy
            dockerfile: gcc.Dockerfile
            args:
                GCC_VERSION: 7.5.0
        image: "uilianries/gcc7-conanfy"
        container_name: gcc7_conanfy
        tty: true
    gcc8-conanfy:
        build:
            context: conanfy
            dockerfile: gcc.Dockerfile
            args:
                GCC_VERSION: 8.4.0
        image: "uilianries/gcc8-conanfy"
        container_name: gcc8_conanfy
        tty: true
    gcc9-conanfy:
        build:
            context: conanfy
            dockerfile: gcc.Dockerfile
            args:
                GCC_VERSION: 9.3.0
        image: "uilianries/gcc9-conanfy"
        container_name: gcc9_conanfy
        tty: true
    gcc10-conanfy:
        build:
            context: conanfy
            dockerfile: gcc.Dockerfile
            args:
                GCC_VERSION: 10.3.0
        image: "uilianries/gcc10-conanfy"
        container_name: gcc10_conanfy
        tty: true
    clang6-conanfy:
        build:
            context: conanfy
            dockerfile: clang.Dockerfile
            args:
                LLVM_VERSION: 6.0.1
        image: "uilianries/clang6-conanfy"
        container_name: clang6_conanfy
        tty: true
    clang7-conanfy:
        build:
            context: conanfy
            dockerfile: clang.Dockerfile
            args:
                LLVM_VERSION: 7.1.0
        image: "uilianries/clang7-conanfy"
        container_name: clang7_conanfy
        tty: true
    clang8-conanfy:
        build:
            context: conanfy
            dockerfile: clang.Dockerfile
            args:
                LLVM_VERSION: 8.0.1
        image: "uilianries/clang8-conanfy"
        container_name: clang8_conanfy
        tty: true
    clang9-conanfy:
        build:
            context: conanfy
            dockerfile: clang.Dockerfile
            args:
                LLVM_VERSION: 9.0.1
        image: "uilianries/clang9-conanfy"
        container_name: clang9_conanfy
        tty: true
    clang10-conanfy:
        build:
            context: conanfy
            dockerfile: clang.Dockerfile
            args:
                LLVM_VERSION: 10.0.1
        image: "uilianries/clang10-conanfy"
        container_name: clang10_conanfy
        tty: true
    clang11-conanfy:
        build:
            context: conanfy
            dockerfile: clang.Dockerfile
            args:
                LLVM_VERSION: 11.1.0
        image: "uilianries/clang11-conanfy"
        container_name: clang11_conanfy
        tty: true
    clang12-conanfy:
        build:
            context: conanfy
            dockerfile: clang.Dockerfile
            args:
                LLVM_VERSION: 12.0.0
        image: "uilianries/clang12-conanfy"
        container_name: clang12_conanfy
        tty: true
    gcc5:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 5.5.0
        image: "uilianries/gcc5"
        container_name: gcc5
        tty: true
    gcc6:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 6.5.0
        image: "uilianries/gcc6"
        container_name: gcc6
        tty: true
    gcc7:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 7.5.0
        image: "uilianries/gcc7"
        container_name: gcc7
        tty: true
    gcc8:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 8.4.0
        image: "uilianries/gcc8"
        container_name: gcc8
        tty: true
    gcc9:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 9.3.0
        image: "uilianries/gcc9"
        container_name: gcc9
        tty: true
        depends_on:
          - base
    gcc10:
        build:
            context: gcc
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 10.3.0
        image: "uilianries/gcc10"
        container_name: gcc10
        tty: true
    clang6:
        build:
            context: clang
            dockerfile: clang6.Dockerfile
            args:
                LLVM_VERSION: 6.0.1
                LLVM_MAJOR: 6.0
        image: "uilianries/clang6"
        container_name: clang6
        tty: true
    clang7:
        build:
            context: clang
            dockerfile: legacy.Dockerfile
            args:
                LLVM_VERSION: 7.1.0
                LLVM_MAJOR: 7
        image: "uilianries/clang7"
        container_name: clang7
        tty: true
    clang8:
        build:
            context: clang
            dockerfile: legacy.Dockerfile
            args:
                LLVM_VERSION: 8.0.1
                LLVM_MAJOR: 8
        image: "uilianries/clang8"
        container_name: clang8
        tty: true
    clang9:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                LLVM_VERSION: 9.0.1
        image: "uilianries/clang9"
        container_name: clang9
        tty: true
    clang10:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                LLVM_VERSION: 10.0.1
        image: "uilianries/clang10"
        container_name: clang10
        tty: true
    clang11:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                LLVM_VERSION: 11.1.0
        image: "uilianries/clang11"
        container_name: clang11
        tty: true
    clang12:
        build:
            context: clang
            dockerfile: Dockerfile
            args:
                LLVM_VERSION: 12.0.0
        image: "uilianries/clang12"
        container_name: clang12
        tty: true
