version: '3'
services:
    base:
        build:
            context: base
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 10.3.0
        image: "uilianries/base"
        container_name: base
        tty: true
    gcc8-conanfy:
        build:
            context: conanfy
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 8.4.0
        image: "uilianries/gcc8-conanfy"
        container_name: gcc8_conan
        tty: true
    gcc9-conanfy:
        build:
            context: conanfy
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 9.3.0
        image: "uilianries/gcc9-conanfy"
        container_name: gcc9_conan
        tty: true
    gcc10-conanfy:
        build:
            context: conanfy
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 10.3.0
        image: "uilianries/gcc9-conanfy"
        container_name: gcc9_conan
        tty: true
    gcc8:
        build:
            context: final
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 8.4.0
        image: "uilianries/gcc8"
        container_name: gcc8
        tty: true
    gcc9:
        build:
            context: final
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 9.3.0
        image: "uilianries/gcc9"
        container_name: gcc9
        tty: true
        depends_on:
          - base
    gcc10:
        build:
            context: final
            dockerfile: Dockerfile
            args:
                GCC_VERSION: 10.3.0
        image: "uilianries/gcc10"
        container_name: gcc10
        tty: true
