name: Build and Deploy
on: [push]
jobs:
  GCC9:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build base image
      run: docker-compose build base
    - name: Build Docker image uilianries/gcc9
      run: docker-compose build gcc9
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    - name: Docker Upload image uilianries/base
      run: docker push uilianries/base
    - name: Docker Upload image uilianries/gcc9
      run: docker push uilianries/gcc9
