name: Build and Deploy
on: [push]
jobs:
  base:
    if: False
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build GCC Base Image
      run: |
        docker pull uilianries/base
        docker build -t uilianries/base base/
    - name: Inspect Docker image uilianries/base
      run: docker inspect uilianries/base
    - name: Docker login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    - name: Docker Upload image uilianries/base
      run: docker push uilianries/base
  conanfy:
    if: False
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [gcc8-conanfy, gcc9-conanfy, gcc10-conanfy]
    steps:
    - uses: actions/checkout@master
    - name: Build ${{ matrix.version }}
      env:
        CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
        CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
      run: docker build -t uilianries/${{ matrix.version }} --build-arg CONAN_PASSWORD=${{ secrets.CONAN_PASSWORD }} --build-arg CONAN_LOGIN_USERNAME=${{ secrets.CONAN_LOGIN_USERNAME }} ${{ matrix.version }}/
    - name: Docker login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    - name: Docker Upload image uilianries/${{ matrix.version }}
      run: docker push uilianries/${{ matrix.version }}
  build:
    if: False
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [gcc10, gcc9, gcc8]
    steps:
    - uses: actions/checkout@master
    - name: Build ${{ matrix.version }}
      run: |
        docker build -t uilianries/${{ matrix.version }} ${{ matrix.version }}/
    - name: Inspect Docker image uilianries/${{ matrix.version }}
      run: docker inspect uilianries/${{ matrix.version }}
    - name: Docker login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    - name: Docker Upload image uilianries/${{ matrix.version }}
      run: docker push uilianries/${{ matrix.version }}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [gcc10, gcc9, gcc8]
    steps:
    - uses: actions/checkout@master
    - name: Test ${{ matrix.version }}
      run: |
        docker build -t uilianries/test --build-arg COMPILER=${{ matrix.version }} test/
        chmod +x test/run.sh
        test/run.sh ${{ matrix.version }}
