name: Build and Deploy
on: [push]
jobs:
  base:
    if: False
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Docker Base Image
      run: |
        docker-compose pull base
        docker-compose build base
    - name: Inspect Docker image uilianries/base
      run: docker inspect uilianries/base
    - name: Docker login
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Docker Upload image uilianries/base
      run: docker push uilianries/base
  conanfy-gcc:
    if: False
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [gcc5-conanfy, gcc6-conanfy, gcc7-conanfy, gcc8-conanfy, gcc9-conanfy, gcc10-conanfy]
    steps:
    - uses: actions/checkout@master
    - name: Build ${{ matrix.version }}
      run: |
        docker-compose pull ${{ matrix.version }}
        docker-compose build --build-arg CONAN_PASSWORD=${{ secrets.CONAN_PASSWORD }} --build-arg CONAN_LOGIN_USERNAME=${{ secrets.CONAN_LOGIN_USERNAME }} ${{ matrix.version }}
    - name: Docker login
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Docker Upload image uilianries/${{ matrix.version }}
      run: docker push uilianries/${{ matrix.version }}
  build-gcc:
    if: False
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [gcc5, gcc6, gcc7, gcc8, gcc9, gcc10]
    steps:
    - uses: actions/checkout@master
    - name: Build ${{ matrix.version }}
      run: |
        docker-compose pull ${{ matrix.version }}
        docker-compose build ${{ matrix.version }}
    - name: Inspect Docker image uilianries/${{ matrix.version }}
      run: docker inspect uilianries/${{ matrix.version }}
    - name: Docker login
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Docker Upload image uilianries/${{ matrix.version }}
      run: docker push uilianries/${{ matrix.version }}
  test-gcc:
    if: False
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [gcc5, gcc6, gcc7, gcc8, gcc9, gcc10]
    steps:
    - uses: actions/checkout@master
    - name: Test ${{ matrix.version }}
      run: |
        docker build -t uilianries/gcc-test --build-arg COMPILER=${{ matrix.version }} test/gcc
        chmod +x test/gcc/run.sh
        test/gcc/run.sh ${{ matrix.version }}
  conanfy-clang:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [clang4-conanfy]
    steps:
    - uses: actions/checkout@master
    - name: Build ${{ matrix.version }}
      run: |
        docker-compose pull ${{ matrix.version }}
        docker-compose build --build-arg CONAN_PASSWORD=${{ secrets.CONAN_PASSWORD }} --build-arg CONAN_LOGIN_USERNAME=${{ secrets.CONAN_LOGIN_USERNAME }} ${{ matrix.version }}
    - name: Docker login
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Docker Upload image uilianries/${{ matrix.version }}
      run: docker push uilianries/${{ matrix.version }}
  build-clang:
    needs: conanfy-clang
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [clang4]
    steps:
    - uses: actions/checkout@master
    - name: Build ${{ matrix.version }}
      run: |
        docker pull ${{ matrix.version }}
        docker-compose build ${{ matrix.version }}
    - name: Inspect Docker image uilianries/${{ matrix.version }}
      run: docker inspect uilianries/${{ matrix.version }}
    - name: Docker login
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Docker Upload image uilianries/${{ matrix.version }}
      run: docker push uilianries/${{ matrix.version }}
  test-clang:
    needs: build-clang
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [clang4]
    steps:
    - uses: actions/checkout@master
    - name: Test ${{ matrix.version }}
      run: |
        docker build -t uilianries/clang-test --build-arg COMPILER=${{ matrix.version }} test/clang
        chmod +x test/clang/run.sh
        test/clang/run.sh ${{ matrix.version }}
